include=~/Documents/dotfiles/fuzzel/lavender.ini

[main]
font=JetBrainsMono Nerd Font:size=7
terminal=foot
icons-enabled=no
#icon-theme=Papirus-Dark
dpi-aware=auto
width=40
horizontal-pad=20
vertical-pad=12
inner-pad=8
lines=8

[colors]
background=1e1e2ed9
text=cdd6f4ff
match=b4befeff               # Lavender — typed match highlight
selection=b4befe40           # Lavender @ ~25% (#entry:selected)
selection-text=b4befeff      # Lavender (#text:selected)
selection-match=cdd6f4ff
border=b4befeff              # Lavender border (wofi window border)
prompt=cdd6f4ff
placeholder=6c7086ff
counter=6c7086ff

[border]
width=2
radius=8                     #border-radius: 8px match
